POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "duonghiep7",
    "password": "h12042001"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "dhhiep2001",
    "password": "h12042001"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "duonghiep7",
    "password": "h12042001"
}

####
POST http://localhost:5000/api/carts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NDRhMWZhODViZjFkMDBjOGU1MjQyMWYiLCJpYXQiOjE2ODI2MTA3OTJ9.ZZ8_2T09aXz4aO0gVpwMshJPNmJigSH5S3b89ndFfs0

{ 
    "title": "Du lich Hawai",
    "description": "4 ngay 3 dem",
    "url": "shopee.com",
}
